name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Stop node project, git pull, start project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/malcolmb-bot
          pm2 stop 0
          git pull https://gabrieljkeller:${{ secrets.GH_KEY }}@github.com/gabrieljkeller/malcolmb-bot
          pm2 start 0
